### ISSUE TITLE
Plugin straight up won't load

### ISSUE THREAD

**Issue by Swirren** [mymindstorm/telekinesis-mod#5]
Title explains it. Using version 1.1.0 on a Paper 1.16.4 server. Doesn't show up under /plugins, and doesn't create its own extracted folder like most other plugins. Help!

**Comment by mymindstorm** [comment]
This is a fabric mod, not a bukkit/spigot plugin.

**Comment by Swirren** [comment]
huh. my bad. don't know why I thought it was paper. sorry! do you think it could be ported to paper? still haven't found anything similar

**Comment by mymindstorm** [comment]
I'm not planning to port this, sorry.

**Comment by Swirren** [comment]
Aw, that sucks. Thanks
